baseURL = "https://tarantini.dev"
title = "Dario Tarantini"
theme = "m10c"
paginate = 5

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"

[params]
    author = "Dario Tarantini"
    description = "Programmatore e appassionato di tecnologia."
    menu_item_separator = " - "
    avatar = "avatar.jpg"
    [[params.social]]
        name = "github"
        url = "https://github.com/dariotarantini"
    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/dariotarantini"
    [[params.social]]
        name = "telegram"
        url = "https://t.me/dariolol"